### ISSUE TITLE
Distribute takeaway challenge form feedback to students

### ISSUE THREAD

**Issue by silvabox** [makersacademy/takeaway-challenge#205]

**Comment by silvabox** [comment]
Sam's script from airport challenge
https://github.com/tansaku/analysis/blob/master/lib/generate_code_review_summaries.rb

**Comment by silvabox** [comment]
No code reviews submitted for:
* https://github.com/makersacademy/takeaway-challenge/pull/209
* https://github.com/makersacademy/takeaway-challenge/pull/208
* https://github.com/makersacademy/takeaway-challenge/pull/206
* https://github.com/makersacademy/takeaway-challenge/pull/204
* https://github.com/makersacademy/takeaway-challenge/pull/201
* https://github.com/makersacademy/takeaway-challenge/pull/199
* https://github.com/makersacademy/takeaway-challenge/pull/191
* https://github.com/makersacademy/takeaway-challenge/pull/185
* https://github.com/makersacademy/takeaway-challenge/pull/184
* https://github.com/makersacademy/takeaway-challenge/pull/182
* https://github.com/makersacademy/takeaway-challenge/pull/179
* https://github.com/makersacademy/takeaway-challenge/pull/177
* https://github.com/makersacademy/takeaway-challenge/pull/174

**Comment by tansaku** [comment]
* [ ] follow up on lack of code reviews
* [ ] address concern about time taken

**Comment by silvabox** [comment]
Link to my scrappy script for compiling the form entries into PR comments:
https://github.com/silvabox/takeaway-challenge/blob/student-feedback-october/generate_code_review_summaries.rb

**Comment by tansaku** [comment]
Rob Stevenson [12:47 PM] 
Hey Sam, no comments on my challenge yet but I know Harry was super busy with his makerthon project so we didn’t get a chance to do a code review

**Comment by silvabox** [comment]
Octavian Rotari [10:35 AM] 
hey Ben how are you? I haven't received my comments yet
Ben [10:36 AM] 
Hi Octavian, who reviewed your code with you?  Did they use the form?
Octavian Rotari [10:50 AM] 
Anthony dell'anno, he wrote just some comments

**Comment by tansaku** [comment]
Harry Dix [10:25 AM] 
Hey Sam, I didn’t get a chance on Monday and then Makerthon took hold, I did speak to Rob and we said we would go through it this week, will ask him if he has the time spare this morning to wizz through it, if that’s suitable?

Sam Joseph [10:25 AM] 
sounds fine - thanks for following up

**Comment by tansaku** [comment]
Harry has now submitted so we could distribute that, but note #213

**Comment by tansaku** [comment]
So I've rerun this removing all the extraneous columns as per the issue of #213 - we got the review from Harry Dix distributed, and Anthony tells me that he didn't use the form for his review of Octavian.

That leaves this set of github ids with no review comments:

* FergusLemon
* ChukaEbi
* asweeney41
* mateja683
* OctavianRotari
* Alaanzr
* RajeevHejib
* dearshrewdwit
* hasulica
* rochester234

I'm concerned that we need to ensure that everyone is getting a review - maybe they are and we just don't know about it.  I think we also need to ensure that high fidelity feedback summaries go out immediately after the review is finished to help students make immediate fixes to their code bases

**Comment by tansaku** [comment]
Have eliminated two from github username mismatches so we are down to:

* FergusLemon
* asweeney41
* mateja683
* OctavianRotari
* Alaanzr
* hasulica
* rochester234

**Comment by tansaku** [comment]
have followed up on slack with all the others above
