### ISSUE TITLE
Twilio does not work for international numbers

### ISSUE THREAD

**Issue by ccfz** [makersacademy/takeaway-challenge#335]
I spend quite a long time trying to make Twilio work this weekend until I found out that it does not work for german numbers. It might be good to put that into the instructions that you need an english number to use the free Twilio.

**Comment by danldb** [comment]
Interesting - I don't know what happened there Casper, but it should be possible to set up.

https://www.twilio.com/help/faq/phone-numbers/which-countries-does-twilio-have-phone-numbers-in-and-what-are-their-capabilities
